### ISSUE TITLE
Github plugin not working as expected.

### ISSUE THREAD

**Issue by wkonkel** [bountysource/frontend#932]
In several use cases, the github plugin does not update titles as expected.

https://github.com/znc/znc/issues/143
https://github.com/znc/znc/issues/120

**Comment by x-a-n-a-x** [comment]
I confirm the problem with the title not getting updated.

https://github.com/OpenRA/OpenRA/issues/4989

https://www.bountysource.com/issues/1450351-add-red-alert-campaign?utm_campaign=plugin&utm_content=tracker%2F36085&utm_medium=issues&utm_source=github

**Comment by rappo** [comment]
@DarthGandalf We pushed some changes and have been monitored since Friday. The broken titles/body issues should not occur again. If you see anything come up, let us know.

@x-a-n-a-x Your issue is related to permissions Bountysource needs from the OpenRA GH Org. We'll follow up with the OpenRA team directly to help them get it resolved.
