### ISSUE TITLE
Stop the mods from destroying posts on bountysource subreddit.

### ISSUE THREAD

**Issue by 3rdwiki** [bountysource/frontend#936]
rappo,

I have tried several times to contact you through reddit. The issue is that you seem to be hell-bent on destroying any 'other' discussion of this website on the reddit website.

Personally, and as a redditor, I take umbridge with this.

How can we talk out of the box if you keep on cancelling all of the posts on reddit, to which people have the ability to comment and leave their mark ?

It gets worse when I note the subreddit on the other forums like discourse/ubuntu and then it looks as-if no one cares about the project enough to post anything - which isn't the case - I know.

Please - let us know the reasoning behind this,  and please respond to the messages that have been set concerning the subreddit: http://www.reddit.com/r/bountysource

**Comment by 3rdwiki** [comment]
@corytheboyd  TBH I think bountysource is suffering from an "All the eggs in one basket" syndrome, where you can't talk about Bsource (FClub) outside the website - is that because there is too much corp-rate thinking (group think)... I dunno.      It's something to consider.

I mean the internet just doesn't and is not imbued to work like that.

The internet is there to bring people on-board.
And as such I'd like to open the discussion to the rest of the vast reddit community.
I have posted a querying post on [/r/bountysource](http://www.reddit.com/r/BountySource/comments/2rh0u3/question_which_of_these_bountysource_bugs_is_best/) about firing up the [bountysource subreddit](http://www.reddit.com/r/BountySource/) along the lines of sorting out what is referred to as the legacy operating system/s that I am keen on.

My only hope for [this post](http://imgur.com/LsELaq1) is that @rappo does not destroy or remove the post - so that in time, others should be able to answer the question .. and it alleviates the need for mailman, messageboards, and the like which I consider "event based" methods of communication which are difficult to follow the discussion from times past, easily. 

afterthought: "My only hope" ... man I almost had a [Quantum Leap flashback](http://imgur.com/gallery/qMe4r).

**Comment by rappo** [comment]
@3rdwiki Thanks for reaching out. Firstly, I don't appreciate the tone you took without doing some fact finding or at least initial discussion (specifically, "you seem to be hell-bent on destroying any 'other' discussion of this website"). Please try to act more cooperatively in the future.

Until the submission you [referenced in your last post](http://www.reddit.com/r/BountySource/comments/2rh0u3/question_which_of_these_bountysource_bugs_is_best/), neither you nor anyone else had submitted anything to that subreddit. Additionally, no posts were ever removed or edited. See:
![image](https://cloud.githubusercontent.com/assets/2245234/5668940/62aeaee0-9728-11e4-8790-115a3d52f255.png)

Please double check what submissions you made, as they did not end up in a post submitted to the Bountysource subreddit. Additionally, the subreddit settings are open and public. Moderation as this point has not been needed because 1) the moderator/s (just me right now) are not required for content to appear 2) no on has made an effort to use the subreddit until this point, so it's merely holding the name.

These are the settings, if you're curious:
![image](https://cloud.githubusercontent.com/assets/2245234/5668800/4d470468-9727-11e4-834b-532beb890946.png)
![image](https://cloud.githubusercontent.com/assets/2245234/5668812/588acc4c-9727-11e4-840c-c6dc32b8bd01.png)

Feel free to talk about Bountysource anywhere and everywhere you like, we make no efforts to control that. There's plenty of healthy discussion on GitHub, various forums, Freenode IRC, and Twitter for example.

**Comment by 3rdwiki** [comment]
OK .. I'll give it a test .. My sincere apologies for my comments as they were not warranted.
I was just curious as to where my posts over the past two/three years had gone to.
My bad - hope you didn't take it personally.

**Comment by rappo** [comment]
@3rdwiki thanks for the follow-up and for understanding. Definitely no hard feelings :)

I'm going to close this Issue, I think we've resolved it. Feel free to ping us if you have any more questions or concerns!

**Comment by 3rdwiki** [comment]
Thanks, I gave $20 to the Ubuntu Projects feed, for doing so well.
It'd be nice if you could head over to the subreddit and answer some of the questions posed. But no-worries if not.
We need discussion people, Discussion!
