### ISSUE TITLE
Add support for Mantis

### ISSUE THREAD

**Issue by kazssym** [bountysource/frontend#944]
I cannot search for issues tracked by Mantis Bug Tracker https://www.mantisbt.org/

I would like Mantis support added to Bountysource.com.

**Comment by c-schmitz** [comment]
Is this really a frontend issue? Can this be accomplished by an external developer?

**Comment by kazssym** [comment]
I don't think this is really a frontend issue but I cannot request such an enhancement for the backend anywhere else. So this is just a reminder in my intention and I didn't post any bounty myself.

**Comment by kazssym** [comment]
How can I use it? Does it just have delays before being deployed?

**Comment by rappo** [comment]
It's live in production. If you search for a URL to a mantis issue it'll detect that it's mantis (just like with GitHub, Bugzilla, etc)

**Comment by kazssym** [comment]
I cannot get http://bugs.caucho.com/view.php?id=5940 correctly detected. What is wrong?

**Comment by yorikvanhavre** [comment]
I cannot get it to work either... I'd like to add our mantis tracker at https://www.freecadweb.org/tracker
to our FreeCAD project. Tried to add the URL above to https://www.bountysource.com/teams/freecad/projects/manage but nothing happens... Suggesting issues by using an URL from the same mantis tracker also doesn't seem to produce any result (the issue is apparently not added). Can someone confirm if the mantis integration is still working, and if yes, how to use it? Thanks!

**Comment by luzpaz** [comment]
+1

**Comment by HoWilgh** [comment]
+1
