### ISSUE TITLE
Modify issue body with a link to Bountysource for every GitHub issue

### ISSUE THREAD

**Issue by schettino72** [bountysource/frontend#953]
As of today it is not easy for a user to place a bounty in an issue that still doesn't have any bounty.

**Comment by rappo** [comment]
This is possible with our "GitHub Plugin" that must be enabled by committers. You can turn it on via https://www.bountysource.com/tools

It looks something like this:
![image](https://cloud.githubusercontent.com/assets/2245234/6343987/a6d0c50c-bba6-11e4-8213-5139d2b02bf3.png)

If this isn't what you mean, feel free to clarify and reopen :).

**Comment by schettino72** [comment]
> If this isn't what you mean, feel free to clarify and reopen :).

That's not what I mean. I already enabled this "Github plugin". The problem is when there is still no bounty for an issue there is no link displayed. For example this issue itself has no link to bountysource, while #926 has a link. 

For an issue with a link it is easy to go to bountysource site and add a bounty. But for an issue without any link I need to manually go to bountysource website and search for project/issue that I want to place a bounty...

Worse than that I expect most users of my project looking at an issue will not be aware that they can add a bounty (even if i put a link on my readme page). So IMO having a link on every issue page is very important. Anyway thats just my opinion thanks for quick answer.

**Comment by rappo** [comment]
@schettino72 That's exactly what the "Modify issue bodies" option will do. If the issue is open, it will link to the Bountysource page similar to this:
![image](https://cloud.githubusercontent.com/assets/2245234/6360439/c8f10c86-bc2e-11e4-9f04-251ef3577e4d.png)

If there's a bounty it'll show the text like the issue you linked in #926. When the issue is closed, if there is no bounty, it will remove the text -- this why there's no link to Bountysource on this issue. The text is removed because closed issues cannot have bounties, only open issues.

**Comment by schettino72** [comment]
ok. I can see it on my project now. It seems it took over 24 hours to show up...
Thanks and sorry for the noise.
