### ISSUE TITLE
Add support for bitbucket

### ISSUE THREAD

**Issue by rwarren** [bountysource/frontend#960]

**Comment by kazssym** [comment]
What is an exact feature this issue is talking about? The Bitbucket Issue Tracker is already (incompletely) supported and by entering an issue URL, Bountysource.com can collect issues from the repository.

Is this issue for either federated login with Bitbucket, more tight integration with Bitbucket, or something else?

**Comment by rwarren** [comment]
This was actually raised by mistake... sorry.
